### ISSUE TITLE
SDK 在哪下载？

### ISSUE THREAD

**Issue by zt199510** [EmilyEdna/CandySugarIII#1]
SDK 在哪下载？

**Comment by EmilyEdna** [comment]
> SDK 在哪下载？

SDK是我的私人库，目前并不打算开源，不过我可以提供一份混淆后的SDK，留下你的邮箱

**Comment by zt199510** [comment]
1033566918@qq.com

**Comment by zt199510** [comment]
SDK能配一份使用说明吗

**Comment by EmilyEdna** [comment]
在你的项目中引入
`		<PackageReference Include="JavaScriptEngineSwitcher.Jint" Version="3.26.1" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
		<PackageReference Include="XExten.Advance" Version="2.2.2.2" />
`
simple music:
`
 var SongItem = MusicFactory.Music(opt =>
                {
                    opt.RequestParam = new Input
                    {
                        PlatformType = PlatformEnum.QQMusic,
                        MusicType = MusicEnum.Song,
                        Search = new MusicSearch
                        {
                            KeyWord = "周杰伦"
                        }
                    };
                }).RunsAsync().Result;
`
SDK Logger:

`your logger class :ISdkLogger
{


}
`

**Comment by EmilyEdna** [comment]
在你项目中引入：

```c#
<PackageReference Include="JavaScriptEngineSwitcher.Jint" Version="3.26.1" />
<PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
<PackageReference Include="XExten.Advance" Version="2.2.2.2" />
```
在你的初始化过程中注册

```c#
NetFactoryExtension.RegisterNetFramework();
```

simple:

```C#
var SongItem = MusicFactory.Music(opt =>
{
    opt.RequestParam = new Input
    {
       PlatformType = PlatformEnum.QQMusic,
       MusicType = MusicEnum.Song,
       Search = new MusicSearch{
          KeyWord = "周杰伦"
          }
      };
 }).RunsAsync().Result;
```

 实现SDK的日志：

```c#
public class Logger :ISdkLogger
{


}
```

**Comment by EmilyEdna** [comment]
> [1033566918@qq.com](mailto:1033566918@qq.com)
SDK套件
[sdk.zip](https://github.com/user-attachments/files/16775909/sdk.zip)
